spring:
  application:
    name: ArcView WoT Bridge

graphql:
  packages:
    - "org.eclipse.lmos.arc.bridge"
    - "org.eclipse.lmos.sdk.model"
    - "org.eclipse.lmos.sdk.agents"
  playground:
    enabled: true

server:
  port: 8300

wot:
  servient:
    http:
      server:
        enabled: false
    websocket:
      server:
        enabled: false